### ISSUE TITLE
Writing observations

### ISSUE THREAD

**Issue by ztsv-av** [mbaske/ml-audio-sensor#4]
Hello @mbaske. Can you explain what part of your code actually writes observations to the agent? I see `Write(ObservationWriter writer)` functions at `AudioSensor.cs` and `AudioSensorProxy.cs` but apparently they are never called? At least I tried to see if they are ever called by some Debug.Log statements, which were never invoked. I want to see which observations are actually processed by the agent. My task is fairly simple, identifying 5 piano keys when played, but no matter what I tried, the agent is not being trained. I also tried your `ChordDetection` example. I did not change anything, just started training using supplied training config, however the model could not train. It just did not converge, the loss kept fluctuating.
Thanks.

**Comment by mbaske** [comment]
Hi - sensors implementing ISensor provide the ```public int Write(ObservationWriter writer)``` method for the ml-agents code. Please see https://docs.unity3d.com/Packages/com.unity.ml-agents@2.0/api/Unity.MLAgents.Sensors.ISensor.html

**Comment by ztsv-av** [comment]
Thanks for your reply. Turns out the problem was with the fact that we need to use `--time-scale 1` when training a model, not with the observations that are supplied to the agent. Great repo btw!
